students/faculty/urls.py
from django.conf.urls import patterns, url

from faculty import views

urlpatterns = patterns('',
    # url(r'^$', views.GroupListView.as_view(), name='group-list'),
    # url(r'^edit/(?P<pk>\d+)$', views.GroupDetailsView.as_view(), name='group-details'),
    # url(r'^edit/(?P<pk>\d+)$', views.StudentUpdateView.as_view(), name='student-edit'),
)

students/students/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from faculty import views, forms
from django.contrib.auth.decorators import login_required

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',
                {'authentication_form': forms.EmailAuthenticationForm,},
                name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    url(r'^$', login_required(views.GroupListView.as_view()),
               name='group-list'),
    url(r'^group/edit/(?P<pk>\d+)$', views.GroupDetailsView.as_view(),
                                     name='group-details'),
    url(r'^group/create', views.GroupCreateView.as_view(),
                                        name='group-create'),
    url(r'^student/create', views.StudentCreateView.as_view(),
                                        name='student-create'),
    url(r'^student/edit/(?P<pk>\d+)$', views.StudentUpdateView.as_view(),
                                       name='student-edit'),
    url(r'^student/delete/(?P<pk>\d+)$', views.StudentDeleteView.as_view(),
                                       name='student-delete'),
    url(r'^admin/', include(admin.site.urls)),
)

students/faculty/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Student(models.Model):
    last_name = models.CharField(u"Фамилия", max_length=30)
    first_name = models.CharField(u"Имя", max_length=20)
    middle_name = models.CharField(u"Отчество", max_length=30)
    date_of_birth = models.DateField(u"Дата рождения")
    id_card_number = models.PositiveIntegerField(u"Номер студенческого билета")
    group = models.ForeignKey("Group", 
                              null=True, 
                              blank=True, 
                              verbose_name=u"Группа")

    class Meta:
        verbose_name = u"Студент"
        verbose_name_plural = u"Студенты"

    def __unicode__(self):
        return u"%s %s %s" % (self.last_name,
                              self.first_name,
                              self.middle_name)


class Group(models.Model):
    name = models.CharField(u"Название группы", max_length=30)
    senior_student = models.OneToOneField(Student,
                                          related_name="senior_student",
                                          null=True, blank=True,
                                          on_delete=models.SET_NULL,
                                          verbose_name=u"Староста")

    class Meta:
        verbose_name = u"Группа"
        verbose_name_plural = u"Группы"

    def __unicode__(self):
        return u"%s" % self.name

students/faculty/forms.py
from django import forms

from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext, ugettext_lazy as _


class EmailAuthenticationForm(AuthenticationForm):
    email = forms.EmailField(max_length=254, label=_("E-mail"))

    def clean(self):
        email = self.cleaned_data.get('email')
        return self.cleaned_data

    # def clean(self):
    #     username = self.cleaned_data.get('username')
    #     password = self.cleaned_data.get('password')
    #     email = self.cleaned_data.get('email')

    #     # if username and password:
    #     if email and password:
    #         # self.user_cache = authenticate(username=username,
    #                                        # password=password)
    #         print 'DEBUG: ', email
    #         self.user_cache = authenticate(email=email,
    #                                        password=password)
    #         print "User is active", self.user_cache.is_active
    #         if self.user_cache is None:
    #             raise forms.ValidationError(
    #                 self.error_messages['invalid_login'],
    #                 code='invalid_login',
    #                 params={'username': self.username_field.verbose_name},
    #             )
    #         elif not self.user_cache.is_active:
    #             raise forms.ValidationError(
    #                 self.error_messages['inactive'],
    #                 code='inactive',
    #             )
    #     print self.get_user()
    #     return self.cleaned_data

students/faculty/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# from django.http import HttpResponseRedirect
# from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse_lazy, reverse
from faculty.models import Group, Student


class GroupListView(ListView):
    model = Group

    def get_context_data(self, **kwargs):
        context = super(GroupListView, self).get_context_data(**kwargs)
        return context


class GroupDetailsView(DetailView):
    model = Group
    template_name = "faculty/group_details.html"

    def get_context_data(self, **kwargs):
        context = super(GroupDetailsView, self).get_context_data(**kwargs)
        return context


class GroupCreateView(CreateView):
    model = Group
    success_url = reverse_lazy('group-list')


class StudentCreateView(CreateView):
    model = Student

    def get_success_url(self):
        return reverse('group-details', args=(self.object.group.id,))


class StudentUpdateView(UpdateView):
    model = Student

    def get_success_url(self):
        return reverse('group-details', args=(self.object.group.id,))


class StudentDeleteView(DeleteView):
    model = Student

    def get_success_url(self):
        return reverse('group-details', args=(self.object.group.id,))

students/templates/faculty/group_details.html
<a href="{% url 'group-list' %}">На главную</a>
<p>Группа: {{ group.name }}</p>
	<table border="1">
		<caption>Список студентов</caption>
		{% for student in group.student_set.all %}
			<tr>
			<td>
				{{student.last_name}} {{ student.first_name }} {{student.middle_name}}
			</td>
			<td>
				<a href="{% url 'student-edit' student.id %}">Изменить</a>
			</td>
			<td>
				<a href="{% url 'student-delete' student.id %}">Удалить</a>
			</td>
			</tr>
		{% empty %}
			<tr><td>Группа пуста</td></tr>
		{% endfor %}
	</table>

students/templates/faculty/group_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Готово" />
</form>

students/templates/faculty/group_list.html
{% if user.is_authenticated %}
    <p>
    	Пользователь: {{ user.username }}
    	<a href="accounts/logout/">Выйти</a>
    </p>
{% else %}
    <p>Welcome, new user. Please log in.</p>
{% endif %}
<h1>Список всех групп</h1>
<table border="1" bordercolor="gray">
	<tr>
		<th>Название</th>
		<th>Староста</th>
		<th>Студентов</th>
	</tr>
{% for group in object_list %}
	<tr>
	{% url 'group-details' group.id as group_url %}
	<td><a href="{{ group_url }}">{{ group.name }}</a></td>
	<td>{{ group.senior_student|default_if_none:"Не назначен" }}</td>
	<td align="center">{{ group.student_set.count }}</td>
	</tr>
{% empty %}
	<tr colspan="3">No groups yet</tr>
{% endfor %}
</table>
<hr>
<a href="{% url 'group-create'%}">Создать новую группу</a>
<a href="{% url 'student-create'%}">Создать нового студента</a>

students/templates/faculty/student_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Подтвердите удаление студента 
    "{{ object.last_name }} {{ object.first_name }} {{ object.middle_name }}"</p>
    <input type="submit" value="Подтверждаю" />
</form>

students/templates/faculty/student_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Готово" />
</form>